export const AppImages = {
  brand_ad: "/assets/images/brand_ad.png",
  classrooms: "/assets/images/classrooms.webp",
  college: "/assets/images/college.webp",
  contact_us: "/assets/images/contact_us.png",
  football: "/assets/images/football.webp",
  home_page_bg: "/assets/images/home_page_bg.png",
  long_logo: "/assets/images/long_logo.webp",
  playstore_download: "/assets/images/playstore_download.webp",
  school: "/assets/images/school.webp",
  short_logo: "/assets/images/short_logo.png",
  student_clubs: "/assets/images/student_clubs.webp",
  webinar: "/assets/images/webinar.webp",
  whatsapp: "/assets/images/whatsapp.png",
  screenshots: {
    dashboard: "/assets/app_screenshots/dashboard.webp",
    features: "/assets/app_screenshots/features.webp",
    chat: "/assets/app_screenshots/chat.webp",
    feed: "/assets/app_screenshots/feed.webp",
    files: "/assets/app_screenshots/files.webp",
    meetings: "/assets/app_screenshots/meetings.webp",
    payments: "/assets/app_screenshots/payments.webp",
  },
  apps: "/assets/icons/apps.svg",
  cloud: "/assets/icons/cloud.webp",
  easy: "/assets/icons/easy.webp",
  flash: "/assets/icons/flash.svg",
  free: "/assets/icons/free.webp",
  mobile: "/assets/icons/mobile.webp",
  price_tag: "/assets/icons/price_tag.svg",
  right_arrow: "/assets/icons/right_arrow.svg",
  rocket: "/assets/icons/rocket.webp",
  secure: "/assets/icons/secure.webp",
  trust: "/assets/icons/trust.webp",
  identity: "/assets/icons/identity.webp",
  money: "/assets/icons/money.webp",
};

export const AppLinks = {
  playstore_link: "https://play.google.com/store/apps/details?id=com.tuft.app",
};
